### ISSUE TITLE
mapping not cleared when user command defined

### ISSUE THREAD

**Issue by Alok** [dhruvasagar/vim-table-mode#106] opened 2016-11-14 01:27 UTC
I have these settings:

```vim
let g:table_mode_tableize_map = '<leader>tz'
nnoremap <buffer> <leader>tz <Plug>(table-mode-tableize)
```

However, `<leader>tt` still activates `tableize`. Does this plugin not turn off mappings if they're already defined?

**Comment by dhruvasagar** [comment] 2016-11-14 04:36
Hi,

Actually the setting `g:table_mode_tableize_map` does not exist, so as of now there isn't a direct way to override that mapping directly. What you're doing here is only providing a new mapping.

However since you've requested it, I will add that. By design, then you will only need to configure the setting, the mapping will be added by the plugin using the setting.

**Comment by dhruvasagar** [comment] 2016-11-14 10:04
Hi,

I needed to refresh my memory on how plug mappings work. Basically you need the following configuration to make it working : 

```vim
nmap <silent> <leader>tz <Plug>(table-mode-tableize)
```

A few things to note : 
* You do not need to set any global option, there doesn't exist one for this use case nor is it requried
* You need to use `nmap` as opposed to `nnoremap` to define your mapping, since `<Plug>` mappings are special mappings which will eventually be further resolved by vim to it's correct mapped representation, in this case it being calling the command `:Tableize`. Using `nnoremap` implies that vim does not try to resolve the given mapping further and uses it as is, so it will not work in this case.
* This is a global mapping, depending on where you apply this mapping the `<buffer>` mapping option may be irrelevant. The `<buffer>` mapping option is usually used in ftplugins while defining plugins for specific buffers, however using that within your vimrc will result in unintended consequences and it will not be available globally as it is designed to be by default.

**Closed by dhruvasagar** 2016-11-14 10:04 UTC
