### ISSUE TITLE
Cannot add the same table.

### ISSUE THREAD

**Issue by sittim** [dhruvasagar/vim-table-mode#91] opened 2016-06-27 14:54 UTC
Few days ago, I made a table, when I re-flow the table, it looked like this:

![selection_018](https://cloud.githubusercontent.com/assets/8825037/16383697/36eaef12-3c54-11e6-96ab-596f60b939d2.png)

Perfect, I was thrilled! But today, I cannot get the same result, When I re-flow the same table it turns into this:

![selection_019](https://cloud.githubusercontent.com/assets/8825037/16383779/7ae93412-3c54-11e6-98b8-4292bcdcebc8.png)

Notice the first two columns are not centred and each column requires more horizontal space. Why would it be?  The only configuration I have is `let g:table_mode_corner = '|'`, in order to make the table markdown compatible.

**Comment by dhruvasagar** [comment] 2016-07-11 07:49
This seems odd, is table mode enabled ? Is the behavior different when Table Mode is or not enabled ?
Will investigate into this.

**Comment by dhruvasagar** [comment] 2016-07-11 08:04
I am not able to reproduce this. How are you 're-flowing' the table ? I am assuming you used `:TableModeRealign` or `<Leader>tr`(default) ?

**Comment by dhruvasagar** [comment] 2016-07-11 08:46
Also, maybe you want to remove and re-add the table separator, or remove spaces manually, since once there are spaces it recognises it as a regular table row and hence doesn't work as you would expect.

Kindly let me know if you are still facing this issue and reopen this issue. Closing it for now.

**Closed by dhruvasagar** 2016-07-11 08:46 UTC

**Comment by sittim** [comment] 2016-07-11 11:46
I think it is because I was trying to use rst plugin, https://github.com/Rykka/riv.vim.  It helps with some of  the things I need to do, but the vim-table-mode is totally awesome, so I was wondering, any way to make the two work together?

**Comment by dhruvasagar** [comment] 2016-07-11 13:50
Did you try removing the spaces on the header separator and try reformatting the table ? Do you still see the issue ? If you're still facing the issue I can try replicating it, only then can I identify & fix possible issues. Kindly let me know, thanks!

**Comment by sittim** [comment] 2016-07-11 15:03
Yes I did try, in fact if you take a look at this file:

https://github.com/sittim/configs/blob/master/test.md

The first table get these spaces, the second table is good.  If I load the following rc file:

https://github.com/sittim/configs/blob/master/.vimrc_test

and open up the table, going to the second table:

`tm`
`tr`

re-flows the second table to look like the first.

**Comment by dhruvasagar** [comment] 2016-07-13 07:27
But in your ~/.vimrc_test you don't have the setting `let g:table_mode_corner = '|'`. If you have that, it should be reformatting correctly (verified)
