### ISSUE TITLE
Text object i| skips last character in cell

### ISSUE THREAD

**Issue by skajfes** [dhruvasagar/vim-table-mode#149] opened 2019-04-15 09:29 UTC
When I want to yank or change cell contents using text object i|, ie: `yi|` or `ci|`, the last character in the cell gets skipped.

**Comment by dhruvasagar** [comment] 2019-04-15 09:31
Can you give an example ? I haven't seen this happen.

**Comment by skajfes** [comment] 2019-04-15 13:13
Alright, minimal example is this:

`| column |`

When I position the cursor on the letter c (or anywhere in the column) and press `di|`, this is the result:

`| n |`

**Comment by dhruvasagar** [comment] 2019-04-15 13:39
Ok this is very odd, I expected some weird scenario so asked for an example, will take a look, thanks for reporting.

**Comment by dhruvasagar** [comment] 2019-04-25 17:20
Hi, I am unable to reproduce this. Which filetype are you facing this issue in ? It may be due to some other plugin with conflicting mapping.

**Comment by skajfes** [comment] 2019-04-26 07:41
OK, I looked a little better at my config and found the source of the issue. I use `mswin.vim` in my config. 
And it sets the selection option to exclusive. Adding `set selection=inclusive` to my config fixed the issue for me. Side benefit is that the inclusive selection makes much more sense, since the cursor for selection and normal mode is a block covering the letter.

**Comment by dhruvasagar** [comment] 2019-04-26 07:52
Good to know, closing the issue for now.

**Closed by dhruvasagar** 2019-04-26 07:52 UTC
